FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /workspace

COPY dine-in-api/src ./src

RUN dotnet restore ./src/DineIn.API/DineIn.API.csproj
RUN dotnet publish ./src/DineIn.API/DineIn.API.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "DineIn.API.dll"]
