services:
  - type: web
    name: dine-in-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    dockerContext: .
    branch: main
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: DineIn.API
      - key: Jwt__Audience
        value: DineIn.Admin
      - key: Jwt__ExpiresInHours
        value: "8"
